# meta
exp_name: 256_median_new_metallic_final
output_name: textures_bg
mode: test
cuda: False
ngpu: 1
gpus: '0'

# data
dataset: material
data_root: /media/raid/dsubias/data_45k
out_root: /media/raid/dsubias
train_file: attributes_dataset_train_new_median_illum.txt
val_file: attributes_dataset_synthetic.txt
test_file: textures.txt
crop_size: 480
image_size: 256
data_augmentation: True
mask_input_bg: True
histogram: True
histogram_color_type: hsv
add_bg: False
video: False

# model
g_conv_dim: 32
d_conv_dim: 32
d_fc_dim: 256
g_layers: 5
d_layers: 5
shortcut_layers: 4
stu_kernel_size: 3
use_stu: True
deconv: False
one_more_conv: True
checkpoint: 55500 #56250

# training
batch_size: 8
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 7
ld_n_critic: 10
thres_int: 1.0
thres_edition: 1.0
g_xavier_init: False
d_xavier_init: False
ld_xavier_init: False 
use_d: True

# tradeoff parameters
lambda_gp: 10
lambda_1: 50 # att discriminator (original value = 1)
lambda_2: 100 # att generator (original value = 10)
lambda_3: 1000 # reconstruction generator (original value = 100)

# attributes
att_activation: sigmoid # tanh, sigmoid or 
att_loss: l1 # l1, binary_cross_entropy or cross_entropy
att_max: 1
att_min: 0
num_samples: 9
attrs: [ metallic ]
uniform: True
default_att: 0.5

# iterations
max_epochs: 50
lr_decay_iters: 55000

# steps:
summary_step: 500
sample_step: 2500
checkpoint_step: 2500