# meta
exp_name: final_step2_glossy
network: FaderNetWithNormals2Steps
mode: train
cuda: true 
ngpu: 1
checkpoint: ~

# data
dataset: material
data_augmentation: True
data_root: /media/raid/dsubias/data/rendering_materials/renders/datasets_allshapes/renders_by_geom_ldr/network_dataset/
#data_root: /home/johanna/Documents/rendering_materials/renders/datasets_allshapes/network_dataset/
data_root: /media/raid/dsubias/data/rendering_materials/renders/datasets_allshapes/renders_by_geom_ldr/network_dataset/
#data_root: /Users/delanoy/Documents/postdoc/project1_material_networks/dataset/renders_by_geom_ldr/
crop_size: 480
image_size: 256
img_channels: 4
mask_input_bg: True

#which part activate
use_latent_disc: true
use_image_disc: true
GAN_style: "classif"
rec_loss: 'l1' #Can be l1, l2, perceptual

#### model (FaderNet)
#dim of the network
g_conv_dim: 32
d_conv_dim: 32
d_fc_dim: 256
max_conv_dim: 512
vgg_like: 0 #True
g_layers: 4
d_layers: 5
first_conv: True
n_bottlenecks: 3
all_feat: True
#divide into branches, skip connections, where to put the attributes
skip_connections: 0
n_attr_deconv: 1 #in how many deconv layer add the attribute:0 = no attribute, 1=normal (just concat to bneck)
n_concat_normals: 4
#other
attrs: [glossy]
faderNet_checkpoint: lightning_logs/version_6/checkpoints/epoch=399-step=105199.ckpt


# training (FaderNet)
batch_size: 32
beta1: 0.9
beta2: 0.999
g_lr: 0.0001
d_lr: 0.0001
ld_lr: 0.000025
n_critic: 7
n_critic_ld: 10
gan_mode : wgangp
lambda_adv : 0.02
lambda_adv_classif : 3
lambda_gp: 10
lambda_G_tv: 0.0
lambda_G_rec: 1
lambda_G_latent: 2.5
lambda_G_perc: 0
lambda_G_style: 0
lambda_LD: 1
d_lamdba_adv: 1
d_lambda_classif: 3
d_lambda_match: 1

max_epoch: 300
lr_decay_iters: 100000

# steps:
#33 iter per batch
summary_step: 100
sample_step: 2000
checkpoint_step: 5000
