# meta
exp_name: 256_mean_illum_metallic_org
mode: test
split: True
cuda: True
ngpu: 1
gpus: '1'

# data
dataset: material
data_root: 'data_45k'
out_root: '/media/raid/dsubias'
train_file: 'attributes_dataset_train_new_median_illum.txt'
test_file: 'attributes_dataset_test_full_new_illum.txt'
crop_size: 480
image_size: 256
data_augmentation: True
mask_input_bg: True
histogram: True
histogram_color_type: 'hsv'
add_bg: True
add_org: True
video: False
plot_metrics: True

# model
g_conv_dim: 32
d_conv_dim: 32
d_fc_dim: 256
g_layers: 5
d_layers: 5
shortcut_layers: 4
stu_kernel_size: 3
use_stu: True
deconv: False
one_more_conv: True
checkpoint: 26250

# training
batch_size: 32
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 7
ld_n_critic: 10
thres_int: 1.0
thres_edition: 1.0
g_xavier_init: False
d_xavier_init: False
ld_xavier_init: False 
use_ld: False

# tradeoff parameters
lambda_gp: 10
lambda_1: 10 # att discriminator (original value = 1)
lambda_2: 100 # att generator (original value = 10)
lambda_3: 1000 # reconstruction generator (original value = 100)
lambda_4: 1 # adversarial discriminator
lambda_5: 1 # adversarial generator

# attributes
att_activation: 'sigmoid' # 'tanh', 'sigmoid' or ''
att_loss: 'l1' # 'l1', 'binary_cross_entropy' or 'cross_entropy'
att_max: 1
att_min: 1
num_samples: 1
att_neg: False
att_diff: False
attrs: [ metallic ]
uniform: True
default_att: 0.5

# iterations
max_epochs: 40
lr_decay_iters: 100000000

# steps:
summary_step: 100
sample_step: 750
checkpoint_step: 750
