# meta
exp_name: stgan_0-1_128_178_d45_newus_glossy
mode: train
split: True
cuda: True
ngpu: 1

# data
dataset: material
data_root: 'data_45k'
train_file: 'attributes_dataset_train_new_median.txt'
test_file: 'attributes_dataset_test_new_daniel.txt'
crop_size: 178
image_size: 128
data_augmentation: True
mask_input_bg: True

# model
g_conv_dim: 64
d_conv_dim: 64
d_fc_dim: 1024
g_layers: 5
d_layers: 5
shortcut_layers: 3
stu_kernel_size: 3
use_stu: True
one_more_conv: True
attrs: [glossy]
checkpoint: 140000

# training
batch_size: 32
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 5
thres_int: 0.5
lambda_gp: 10
lambda1: 1
lambda2: 10
lambda3: 100
max_iters: 400000
lr_decay_iters: 800000

# steps:
summary_step: 100
sample_step: 10000
checkpoint_step: 10000