# meta
exp_name: prueba #256_480_d45_small_4_hist_lrd
mode: train
split: True
cuda: True
ngpu: 1

# data
dataset: material
data_root: 'data_45k'
train_file: 'attributes_dataset_train_new_median.txt'
test_file: 'attributes_dataset_test_new_daniel.txt'
crop_size: 480
image_size: 256
data_augmentation: True
mask_input_bg: True
att_max: 2
att_min: -1
num_samples: 9
histogram: True
att_diff: True

# model
g_conv_dim: 32
d_conv_dim: 32
d_fc_dim: 1024
g_layers: 5
d_layers: 5
shortcut_layers: 4
stu_kernel_size: 3
use_stu: True
one_more_conv: True
attrs: [glossy]
checkpoint: ~

# training
batch_size: 32
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 5
thres_int: 0.5
lambda_gp: 10
lambda1: 1
lambda2: 10
lambda3: 100
max_iters: 50000
lr_decay_iters: 40000

# steps:
summary_step: 100
sample_step: 1
checkpoint_step: 10000