# meta
exp_name: debug_metallic #256_median_new_glossy_final
mode: train # train, edit_images, edit_video or plot_metrics
cuda: True
ngpu: 1
gpus: '0'

# data
dataset: material
data_root: /home/graphics/dsubias/work_directory/data_45k
out_root: /home/graphics/dsubias/work_directory/FaderNetworks-Materials
train_file: attributes_dataset_train_new_median_illum.txt
val_file: attributes_dataset_synthetic.txt
crop_size: 480
image_size: 256
data_augmentation: True
mask_input_bg: True
add_bg: False
test_folder: ~ # Not used in training

# model
g_conv_dim: 32
d_conv_dim: 32
d_fc_dim: 256
g_layers: 5
d_layers: 5
shortcut_layers: 4
stu_kernel_size: 3
use_stu: True
deconv: False
one_more_conv: True

# training
batch_size: 32
beta1: 0.5
beta2: 0.999
g_lr: 0.0002
d_lr: 0.0002
n_critic: 7
ld_n_critic: 10
thres_int: 1.0
use_d: True
checkpoint: ~
att_min: 0.
att_max: 1.
num_samples: 9

# tradeoff parameters
lambda_gp: 10
lambda_1: 50 # att discriminator (original value = 1)
lambda_2: 100 # att generator (original value = 10)
lambda_3: 1000 # reconstruction generator (original value = 100)

# attributes
attrs: [ metallic ]
uniform: True
default_att: 0.5

# iterations
max_epochs: 50
summary_step: 100
sample_step: 750
checkpoint_step: 750
