from .faderNet import FaderNet
from .normalUnet import NormalUnet
from .faderNet_with_normals import FaderNetWithNormals
from .faderNet_with_normals_2steps import FaderNetWithNormals2Steps
from .faderNet_with_normals_illum import FaderNetWithNormalsAndIllum
from .lightningModule import FaderNetPL